### ISSUE TITLE
Inject incident to statuspage

### ISSUE THREAD

**Issue by miklosmuller** [sbecker59/terraform-provider-statuspage#45]
I would like to know whether it is possible to inject incidents to Atlassian Statuspage with terraform. I cannot seem to do that.

### Terraform Version
Terraform Cloud

### Affected Resource(s)
- statuspage_incident

### Terraform Configuration Files
main.tf:
terraform {
  required_providers {
    statuspage = {
      source  = "sbecker59/statuspage"
    }
  }
}

provider "statuspage" {
  api_key = "concealed"
}

resource "statuspage_incident" "test" {
  id = "test"
}

### Debug Output
Terraform v0.15.4
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mInvalid or unknown key[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with statuspage_incident.test,
[31m│[0m [0m  on main.tf line 28, in resource "statuspage_incident" "test":
[31m│[0m [0m  28:   id = [4m"test"[0m[0m
[31m│[0m [0m
[31m╵[0m[0m


### Panic Output
n/a

### Expected Behavior
A basic incident injected to statuspage?

### Actual Behavior
Terraform plan bails out with error

### Steps to Reproduce
1. Connect Terraform Cloud to GitHub
2. commit main.tf
3. See planning failed.

### Important Factoids
n/a

### References
n/a

**Comment by sbecker59** [comment]
Thanks for this issue.

Indeed, it is a mistake on my part. :poop:
There should not be the `incident resource` available at [registry.terraform.io](https://registry.terraform.io/providers/sbecker59/statuspage/latest).
I am currently working :construction: on this resource. I hope to be able to make it available next week.

**Comment by sbecker59** [comment]
The new version of the provider `0.5.0` included now the management of the [statuspage_incident resources](https://registry.terraform.io/providers/sbecker59/statuspage/latest/docs/resources/incident).

**Comment by miklosmuller** [comment]
Thank you for the effort
